files: ^perun/|^tests|^tests-perf
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
        types: [ file, python ]
    -   id: trailing-whitespace
        types: [ file, python ]
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        types: [file, python]
